CREATE TABLE commits(
    id INT AUTO_INCREMENT PRIMARY KEY,
    teamid INT FOREIGN KEY,
    userid INT FOREIGN KEY,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
